version: '3.8'

services:

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ./api-gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
